### ISSUE TITLE
feature size of a8a dataset may be wrong

### ISSUE THREAD

**Issue by ethan-funny** [tobegit3hub/tensorflow_template_application#27]
Hi, in the file `sparse_classifier.py`, feature size is assigned to 124 for a8a dataset.

```
flags.DEFINE_integer("feature_size", 124, "Number of feature size")
```
However, I think the feature size should be 123 according to [this website](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/).

Am I right?

**Comment by tobegit3hub** [comment]
Thanks @ethan-funny .

You are right the feature size of a8a dataset is `123` which is from `1 to 123`. However, TensorFlow needs to define the array to contain all the feature ids which is from `1 to 123.` The array is 0-based and we need to initialize with the size of `124` to support the id of `123`.

Otherwise, you will get this error if you change the size from `124` to `123`.

<img width="1440" alt="screen shot 2017-06-21 at 12 02 58 pm" src="https://user-images.githubusercontent.com/2715000/27366681-47f8833c-567a-11e7-8ec0-fd9bce400401.png">

**Comment by ethan-funny** [comment]
Thanks @tobegit3hub .
