### ISSUE TITLE
Missing 'streaming_auc'

### ISSUE THREAD

**Issue by hzwave** [tobegit3hub/tensorflow_template_application#7]
Hi there, I downloaded deep_recommend_system for study. But failed to run cancer_classifier.py. The following is what I got. Please anybody advise what is the problem? Thanks!

Use the model: wide_and_deep
Use the optimizer: adagrad
Use the model: wide_and_deep
Traceback (most recent call last):
  File "cancer_classifier.py", line 203, in <module>
    _, auc_op = tf.contrib.metrics.streaming_auc(validate_softmax,
AttributeError: 'module' object has no attribute 'streaming_auc'

**Comment by tobegit3hub** [comment]
Duplicated with https://github.com/tobegit3hub/deep_recommend_system/issues/2 . 

I highly recommend to upgrade TensorFlow to 0.9+ since 0.11.0 is released recently. If you don't want to re-install TensorFlow, commenting out all the lines about `auc` will work but you lose the functionality to check `auc` while training.

**Comment by hzwave** [comment]
Thanks a lot for timely feedback. I upgrade tensorflow to 0.11.0 and it works.

**Comment by tobegit3hub** [comment]
Great! I'm glad that it helps 😃
